plugins {
    id("com.android.application")
    id("kotlin-android")
}

android {
    defaultConfig {
        minSdkVersion(23)
    }
    buildFeatures {
        viewBinding true
    }

    namespace "com.nhaarman.acorn.samples.hellosharedata"
}

dependencies {
    implementation project(":ext-acorn-android-appcompat")
    implementation project(":ext-acorn-rx")

    implementation libs.androidx.core.ktx

    implementation libs.rxjava2
    implementation libs.rxkotlin2
    implementation libs.rxandroid2

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.appcompat

    implementation libs.picasso

    testImplementation libs.expectkt
    testImplementation libs.mockito.kotlin
    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine

    debugImplementation project(":ext-acorn-android-testing")
    androidTestImplementation libs.junit4
    androidTestImplementation libs.expectkt
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.espresso.contrib
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
}
