#!/usr/bin/env bash
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell input keyevent 224
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global window_animation_scale 0
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global transition_animation_scale 0
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global animator_duration_scale 0

./gradlew test lintKotlin :samples:hello-world:lintRelease :samples:hello-navigation:lintRelease :samples:hello-staterestoration:lintRelease :notes-app-bravo-android:lintRelease :notes-app:aac-navigation:lintRelease :notes-app:cicerone:lintRelease :notes-app:conductor:lintRelease :notes-app:mosby:lintRelease publishToMavenLocal transformDexArchiveWithDexMergerForDebug && ./gradlew cCheck mergeAndroidReports --continue --max-workers=1

adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global window_animation_scale 1
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global transition_animation_scale 1
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global animator_duration_scale 1
