#!/usr/bin/env bash
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell input keyevent 224
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global window_animation_scale 0
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global transition_animation_scale 0
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global animator_duration_scale 0

./gradlew test \
    ktlint \
    :ext-bravo-android:lint \
    :ext-bravo-android-testing:lint \
    :ext-bravo-android-timber:lint \
    :ext-bravo-android-lifecycle:lint \
    :samples:hello-world:lintRelease \
    :samples:hello-navigation:lintRelease \
    :samples:hello-staterestoration:lintRelease \
    :samples:hello-transitionanimation:lintRelease \
    :samples:hello-startactivity:lintRelease \
    :samples:hello-sharedata:lintRelease \
    :samples:notes-app:android:lintRelease \
    publishToMavenLocal \
    packageDebugAndroidTest \
    --rerun-tasks \
    && ./gradlew cCheck --max-workers=1

adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global window_animation_scale 1
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global transition_animation_scale 1
adb devices | tail -n +2 | cut -sf 1 | xargs -I {} adb -s {} shell settings put global animator_duration_scale 1
