version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Tests
          command: .circleci/test.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: gradle-wrapper
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: acorn/build/reports
          destination: acorn/reports
      - store_artifacts:
          path: acorn-android/build/reports
          destination: acorn-android/reports
      - store_artifacts:
          path: ~/.m2
          destination: m2
