plugins {
    id("com.android.application")
    id("kotlin-android")
}

android {
    defaultConfig {
        minSdkVersion(21)
    }
    buildFeatures {
        viewBinding true
    }

    namespace "com.nhaarman.acorn.notesapp.android"

    lintOptions {
        /*
         This module is chosen to act as a Lint leaf for acorn and acorn-android.
         See https://groups.google.com/forum/#!msg/lint-dev/RGTvK_uHQGQ/FjJA12aGBAAJ
         */
        checkDependencies true
    }
}

repositories {
    mavenLocal()
}

dependencies {
    implementation project(":ext-acorn")
    implementation project(":ext-acorn-rx")
    implementation project(":ext-acorn-android-appcompat")
    implementation project(":ext-acorn-android-timber")

    implementation project(":samples:notes-app")

    implementation libs.androidx.core.ktx

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.appcompat

    implementation libs.rxjava2
    implementation libs.rxkotlin2
    implementation libs.rxandroid2

    implementation libs.rxbinding3
    implementation libs.rxbinding3.appcompat

    implementation libs.timber

    debugImplementation project(":ext-acorn-android-testing")
    androidTestImplementation libs.junit4
    androidTestImplementation libs.expectkt
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.espresso.contrib
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
}
