plugins {
    id("org.jetbrains.kotlin.jvm")
}

dependencies {
    implementation project(":ext-acorn")
    implementation project(":ext-acorn-rx")

    api libs.rxjava2
    implementation libs.rxkotlin2

    testImplementation project(":ext-acorn-testing")
    testImplementation libs.junit.jupiter.api
    testImplementation libs.mockito.kotlin
    testImplementation libs.expectkt
    testImplementation libs.junit.jupiter.engine
}
