plugins {
    id("com.android.application")
    id("kotlin-android")
}

android {
    defaultConfig {
        minSdkVersion(21)
    }
    buildFeatures {
        viewBinding true
    }

    namespace "com.nhaarman.acorn.samples.helloworld"
}

dependencies {
    implementation project(":ext-acorn-android")


    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.appcompat

    implementation libs.timber

    testImplementation libs.expectkt
    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine

    debugImplementation project(":ext-acorn-android-testing")
    androidTestImplementation libs.junit4
    androidTestImplementation libs.expectkt
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.espresso.contrib
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
}
