plugins {
    id("org.jetbrains.kotlin.jvm")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    compileOnly libs.android.lint.api
    compileOnly libs.android.lint.checks

    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.engine
    testImplementation libs.android.lint
    testImplementation libs.android.lint.tests
}

jar {
    manifest {
        attributes("Lint-Registry-v2": "com.nhaarman.acorn.lint.AcornIssueRegistry")
    }
}
