plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.gradle.java-library")

    id("org.gradle.maven-publish")
    id("signing")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    api project(":acorn")

    compileOnly libs.androidx.annotation

    testImplementation libs.expectkt
    testImplementation libs.mockito.kotlin
    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.engine
}
