name: Pull request
on:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK components
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: ktlint
        run: bash ./ktlint "**/src/**/*.kt" --color

      - name: Test
        run: |
          .github/workflows/test.sh
